### PR TITLE
Refactor Version 2

### PR DESCRIPTION
**Pull request by Tondeptrai23**
## PR status

> [!WARNING]
> This PR will be merged to continue the development process. The bug will have further investigation.

## Updates

- Reformatted all the XAML files for better readability.
- Updated cursor behavior to change on hover for all clickable items.
- Removed unnecessary files.
- Introduced `Loading` state for all admin tables.
- Fixed an anti-pattern in `ShellPage.xaml.cs` by avoiding async calls in the constructor (Milestone 1).
- Enabled automatic navigation to role-specific pages, ensuring smoother access control. The main page remains the entry point and CANNOT BE REMOVED.
- Resolved a bug causing two windows to appear in different locations when logging in and out.
- Made some small styles changes for better UI/UX.
- Updated color-related properties to use `ThemeResource` for dynamic theme support, replacing `StaticResource` which locked colors at load time (doesn't change after loading).

## Notes:

- From now on, all blocks inside XAML files must follow these structures:

```xml
<Button 
    Style="{ThemeResource AccentButtonStyle}"
    Width="60"
    Command="{x:Bind ViewModel.LoginCommand}"/>
```
Or
```xml
<Button Style="{ThemeResource AccentButtonStyle}" Width="60" Command="{x:Bind ViewModel.LoginCommand}"/>
```

## Known issues

* Application will freeze in admin view if being navigated too many times.

### CODE REVIEW

**Comment by tien4112004** [comment]
> * Enabled automatic navigation to role-specific pages, ensuring smoother access control. The main page remains the entry point and CANNOT BE REMOVED.

Can you hide the navigation to main page? If cannot delete it, just hide it.

**Comment by Tondeptrai23** [comment]
> > * Enabled automatic navigation to role-specific pages, ensuring smoother access control. The main page remains the entry point and CANNOT BE REMOVED.
> 
> 
> 
> Can you hide the navigation to main page? If cannot delete it, just hide it.

Already!

**Review by tien4112004 — APPROVED** [review]

**Comment by tien4112004** [comment]
image
Get prepared for the nightmare :D @Tondeptrai23

**Comment by Tondeptrai23** [comment]
New Updates: 

- Resolved bug: UI freezing. 

Reason (I guess, I try it all and the bugs partially gone):

- Improper clean up when navigating between pages (some events are not unsubscribed).
- Some `async void` calls cause it.
- Race conditions when `PaginationControl` sends message even after clicking on other pages.

Complete fix (I guess too):

- Implement `CancellationToken` (too hard, so I give up).
- Temporarily disable button after clicking to prevent multiple operations at a time (too many buttons, I give up, as well).
- Use `UserControl` instead of `Pages`. The use of Pages seems to reduce freezing issues, particularly in the Admin Interface compared to other features (So much Admin Pages, I give up one more time).

Overall, the freezing bug rarely occurs which is acceptable.

**Comment by tien4112004** [comment]
> ## Current Status:
> * The issue rarely occurs now.
> * It happens in admin interface and only during REALLY FAST navigation between pages.
> * This behavior is acceptable, so I have left it as it is.

After testing, the issue still occurs when navigating back from the edit page 3-4 times. Because of this, we should have further investigation.

**Comment by tien4112004** [comment]
> [!WARNING]
> This PR will be merged to continue the development process. The bug will have further investigation.

**Pull request merged**
